//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Village.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_VillageEntities : DbContext
    {
        public E_VillageEntities()
            : base("name=E_VillageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_Contact> Table_Contact { get; set; }
        public DbSet<Table_Feedback> Table_Feedback { get; set; }
        public DbSet<Table_Login> Table_Login { get; set; }
        public DbSet<Table_Registration> Table_Registration { get; set; }
    }
}
