//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Village.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Registration
    {
        public int ID { get; set; }
        public string Profile_Picture { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string DOB { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string Registration_Date { get; set; }
    }
}
